workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Build Flutter APK
        script: |
          $FLUTTER_ROOT/bin/flutter clean && $FLUTTER_ROOT/bin/flutter pub get && $FLUTTER_ROOT/bin/flutter build apk --release
          flutter create . --platforms=android --project-name=cardkeeper
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
