workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Build Flutter APK
        script: |
          export PATH="$FLUTTER_ROOT/bin:$PATH"
          flutter pub get
          flutter create . --platforms=android --project-name=cardkeeper
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
